#pragma once

namespace BIBLE_DATA
{
    /// Unique IDs for identifying each book of the Bible in this program.
    /// Having this enum helps separate identification of books in this program
    /// from various string representations (full names, abbreviations, etc.).
    ///
    /// This is defined in a separate header file to avoid circular #includes.
    enum class BibleBookId
    {
        INVALID,
        GENESIS,
        EXODUS,
        LEVITICUS,
        NUMBERS,
        DEUTERONOMY,
        JOSHUA,
        JUDGES,
        RUTH,
        FIRST_SAMUEL,
        SECOND_SAMUEL,
        FIRST_KINGS,
        SECOND_KINGS,
        FIRST_CHRONICLES,
        SECOND_CHRONICLES,
        EZRA,
        NEHEMIAH,
        ESTHER,
        JOB,
        PSALMS,
        PROVERBS,
        ECCLESIASTES,
        SONG_OF_SOLOMON,
        ISAIAH,
        JEREMIAH,
        LAMENTATIONS,
        EZEKIEL,
        DANIEL,
        HOSEA,
        JOEL,
        AMOS,
        OBADIAH,
        JONAH,
        MICAH,
        NAHUM,
        HABAKKUK,
        ZEPHANIAH,
        HAGGAI,
        ZECHARIAH,
        MALACHI,
        MATTHEW,
        MARK,
        LUKE,
        JOHN,
        ACTS,
        ROMANS,
        FIRST_CORINTHIANS,
        SECOND_CORINTHIANS,
        GALATIANS,
        EPHESIANS,
        PHILIPPIANS,
        COLOSSIANS,
        FIRST_THESSALONIANS,
        SECOND_THESSALONIANS,
        FIRST_TIMOTHY,
        SECOND_TIMOTHY,
        TITUS,
        PHILEMON,
        HEBREWS,
        JAMES,
        FIRST_PETER,
        SECOND_PETER,
        FIRST_JOHN,
        SECOND_JOHN,
        THIRD_JOHN,
        JUDE,
        REVELATION
    };
}
